// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0WXNpDyshev5wprb0rl8_--my108qNXA',
    appId: '1:934314493421:web:7d8571707e88bfbdfad3e4',
    messagingSenderId: '934314493421',
    projectId: 'paliz-flutter-firstproject',
    authDomain: 'paliz-flutter-firstproject.firebaseapp.com',
    storageBucket: 'paliz-flutter-firstproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEqXDeRif7ZoJ3O8maXLgJxUuIWRoYdlw',
    appId: '1:934314493421:android:be74dd5dd977b9a0fad3e4',
    messagingSenderId: '934314493421',
    projectId: 'paliz-flutter-firstproject',
    storageBucket: 'paliz-flutter-firstproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs0mp8j8IKpTUw5WqjynU_ITZcbfssYaI',
    appId: '1:934314493421:ios:94142e3b34272c37fad3e4',
    messagingSenderId: '934314493421',
    projectId: 'paliz-flutter-firstproject',
    storageBucket: 'paliz-flutter-firstproject.appspot.com',
    iosClientId: '934314493421-g8jurltt4g0ussihof5n69ads7m8hsbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs0mp8j8IKpTUw5WqjynU_ITZcbfssYaI',
    appId: '1:934314493421:ios:70b3629ce78e984bfad3e4',
    messagingSenderId: '934314493421',
    projectId: 'paliz-flutter-firstproject',
    storageBucket: 'paliz-flutter-firstproject.appspot.com',
    iosClientId: '934314493421-92oq0nd3i2qejob6qhal7qu2c6dn8ql2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjects.RunnerTests',
  );
}
